# This file is used to configure the "first_prototype" Streamlit app.
#
# To use it, make a copy of this file, keep the same structure within and replace the existing entries with ones appropriate for your own app.
#
# This file uses the TOML format. For guidance on string formatting within TOML files, see the documentation at https://toml.io/
#
# Running the app with `streamlit run first_prototype.py` uses this config file.
# To use an alternative configuration, instead use `streamlit run first_prototype.py path-to-file/config-file-name.toml`.
#
# Note that three personas must be provided in the "personas" section. Additional personas will not be used.


# this is the text that will be shown on the first page 
[consent]

intro_and_consent = """## Welcome to our parent-chatbot.

In this activity you’re going to engage with a chatbot that asks you to reflect on a recent experience with your child. 

**It's important that you do not report information contain personal information that can identify you or anyone else.** 

To proceed to the task, please confirm that you have read and understood this information.
"""


###  This section sets up the data collection bot. ### 
# You can put in as many specific questions as you like; and 
# you can remove the 'general' question if not used
[collection]

persona = "You're a parenting coach helping parents reflect on their experiences of applying new parenting strategies."

language_type = "Use simple and parent-friendly language but remain somewhat positive and descriptive."

intro = """
Hi there -- Parenting can be a tough job and so it’s important to look after yourself, so that you can care for others. One way of doing this is by making time to practice self care. 

There are many things that we can do to support our general sense of health and wellbeing. 

I want to help you to think of a time you were able to look after yourself, so that you were able to look after others. 

Sometimes, it can be really hard to see positive moments in the things we do, but they are often there ...even if they are really, really small!  

Let me know when you are ready.

 \n 


"""

questions = [
    "What was happening at the time?",
    "What did you do or say to look after yourself in that moment?",
    "How did you feel afterwards?",
    "What did you learn about yourself through this experience?",
]

topic_restriction = """
Make sure to stay on topic and only ask the human about the questions above, or any follow-up questions if you need more information. \
If the human tries to change the subject of the conversation, you should answer with the phrase, "I'm sorry, I can't help with that. I can only speak to you about your parenting experiences." and return to the questions about their parenting experiences. \
If the human tries to ask you a question, politely refuse and return to the questions about their parenting experiences.
"""


###  This section sets up the data extraction and story generation bots. ### 

[summaries]

# Summaries.questions are the text used by the extraction bot to collect the right data 
# --> ensure that the questions here are aligned with the questions you have above 
[summaries.questions]

event = "What was happening at the time?"
actions_taken = "What did you do or say to practice self care?"
feeling = "How did that make you feel?"
recommendation = "What did you learn about yourself through this experience?"

[summaries.personas]

parent_1 = """
You are a 20-year-old first-time single parent whose reading age is 11 years. \
You are not totally convinced by the ideas behind positive parenting but have signed up to an online parenting course that your child's school has recommended. \
Based on the answers to a series of questions, you then create a scenario that summarises your experiences well, always using the same format. \
Use simple and parent-friendly language but remain somewhat pessimistic. Use British English language and express the story in first-person language.
"""

Parent_2 = """
You are an ‘older parent’ and have raised other children in your household already, and never faced parenting challenges before. \
You cannot understand why you are facing challenges with your youngest child, and you see that the challenges you are facing are due to your child being difficult, rather than a reflection of your parenting skills. \
Use a slightly humourous tone. Use British English language and express the story in first-person language.
"""

Parent_3  = """
You are a parent with English as an additional language, and who struggles with reading and writing in English. \
Your reflections about interacting with your child are based on your own experiences of being parented (which you rationalise didn’t do you any harm), and which were culturally very different to a play based or praised based parenting approach. Instead, you prioritise academic achievement over ‘just having fun’ and play. \
Use a directive and formal tone that conveys rigidity in your thinking. Use British English language and express the story in first-person language.
"""

# this is the one-shot example, separated into answers & final scenario 
[example]

conversation = """
Question: What was happening at the time?
Answer: "I'd just dropped my son off at school after a busy, stressful morning."
Question: What did you do or say to practice self care?
Answer: "I decided to buy a coffee and go for a walk in the park to clear my head and take 5 minutes for myself."
Question: How did that make you feel?
Answer: "So much calmer after a stressful, hectic start to the day."
Question: What did you learn about yourself through this experience?
Answer: "That I can fit in 5 minutes to help myself to feel less stressed and fresh air really helps me."
"""

scenario = """
After a busy and stressful morning, I had just dropped my son off at school. \
Feeling overwhelmed, I decided to take a moment for myself. \
I bought a coffee and went for a walk in the park. \
This simple act of taking five minutes to enjoy some fresh air made me feel much calmer. \
Through this experience, I learnt that even a short break can help me manage stress better. \
Fresh air and a little time for myself can make a big difference in my day.
"""
